spring:
  application:
    name: CHAT
  profiles:
    active: service
  config:
    import: optional:configserver:http://223.130.150.136:8888

  kafka:
    bootstrap-servers:  kafka-cluster-0.kafka-cluster:9092,kafka-cluster-1.kafka-cluster:9092, kafka-cluster-2.kafka-cluster:9092,kafka-cluster-3.kafka-cluster:9092, kafka-cluster-4.kafka-cluster:9092,kafka-cluster-5.kafka-cluster:9092, kafka-cluster-6.kafka-cluster:9092,kafka-cluster-7.kafka-cluster:9092, kafka-cluster-8.kafka-cluster:9092
    producer:
      retries: 3 # 전송 실패 시 재시도 횟수
      acks: all # 모든 복제본이 데이터를 수신할 때까지 기다림
    consumer:
      group-id: chat-group
      properties:
        spring.json.value.default.type: com.example.chat.model.ChatMessage
      auto-offset-reset: earliest # 가장 이른 메시지부터 소비
      enable-auto-commit: true # 자동 커밋 설정
server:
  port: 8081
  ssl:
    key-store: classpath:tetripscert.p12
    key-store-password: xpxmflqtm
    key-store-type: PKCS12