apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8081
  selector:
    app: chat-service
