apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: tetrips-msa-np-w-5i0a # 다른 노드 이름으로 변경 필요
      containers:
        - name: chat-service
          image: honggyun/tetrips-chat-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://chatuser:chatpassword@mongo-service/chatdb
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: PLAINTEXT://:9092,INSIDE://:9093
