apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: inside
      port: 9093
      targetPort: 9093
    - name: jmx
      port: 1099
      targetPort: 1099
  selector:
    app: kafka-cluster