apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      nodeSelector:
        kubernetes.io/hostname: tetrips-kafzoo-np-w-5i5v
      containers:
        - name: kafka-manager
          image: hlebalbau/kafka-manager:latest
          ports:
            - containerPort: 9000
          env:
            - name: ZK_HOSTS
              value: zookeeper.default.svc.cluster.local:2181
            - name: APPLICATION_SECRET
              value: "some-random-secret"
            - name: KM_AUTH_ENABLED
              value: "false"  # 인증 비활성화, 필요에 따라 수정
