apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id=${POD_NAME}
    listeners=PLAINTEXT://9092,INSIDE://:9093
    advertised.listeners=PLAINTEXT://:9092,INSIDE://:9093
    inter.broker.listener.name=INSIDE
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,INSIDE:PLAINTEXT
    zookeeper.connect=zookeeper.default.svc.cluster.local:2181
    num.partitions=180
    default.replication.factor=3
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
