apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id=${HOSTNAME##*-}
    listeners=PLAINTEXT://0.0.0.0:9092
    log.dirs=/var/lib/kafka
    advertised.listeners=PLAINTEXT://kafka-cluster-$(POD_NAME).kafka.default.svc.cluster.local:9092
    zookeeper.connect=zookeeper-0.zookeeper.kafka-namespace.svc.cluster.local:2181,zookeeper-1.zookeeper.kafka-namespace.svc.cluster.local:2181,zookeeper-2.zookeeper.kafka-namespace.svc.cluster.local:2181
    num.partitions=180
    default.replication.factor=3
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
